pipeline {
    agent any
    environment { NODEJS = 'node22' }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install & Lint') {
            steps {
                dir('client') {
                    nodejs(NODEJS) {
                        sh 'npm ci'
                        sh 'npm run lint || true'
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t car-rental-client:latest ./client'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker rm -f car-rental-client || true

                    docker run -d \
                        --name car-rental-client \
                        -p 8100:8100 \
                        -e API_URL=http://car-rental-server:5000 \
                        car-rental-client:latest
                '''
            }
        }
    }
}
