pipeline {
    agent any
    environment { NODEJS = 'node22' }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install & Lint') {
            steps {
                dir('server') {
                    nodejs(NODEJS) {
                        sh 'npm ci'
                        sh 'npm run lint || true'
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t car-rental-server:latest ./server'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker rm -f car-rental-server || true

                    docker run -d \
                        --name car-rental-server \
                        -p 5000:5000 \
                        --env-file server/.env \
                        car-rental-server:latest
                '''
            }
        }
    }
}
